[package]
name = "frontend"
version = "0.1.0"
authors = ["Aadi Deshpande <aadi.deshpande@gmail.com>"]
edition = "2019"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
seed = "^0.4.0"
serde = "^1.0.0"
wasm-bindgen = "^0.2.0"

shared = { path = "../shared" }

